---
- name: check os
  hosts: prod_servers
  become: yes
  vars:
    messge1: privet

  tasks:
  - debug:
      var:  ansible_distribution

  - shell: uptime
    register: time
  - debug:
      var: time.stdout